# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/protos/calculate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/protos/calculate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1emodules/protos/calculate.proto\"?\n\x10\x43\x61lculateRequest\x12\x14\n\x0c\x66irst_number\x18\x01 \x01(\x05\x12\x15\n\rsecond_number\x18\x02 \x01(\x05\"\x85\x01\n\x0e\x43\x61lculateReply\x12&\n\x06result\x18\x01 \x01(\x0b\x32\x16.CalculateReply.Result\x1aK\n\x06Result\x12\x0b\n\x03\x61\x64\x64\x18\x01 \x01(\x05\x12\x10\n\x08multiply\x18\x02 \x01(\x05\x12\x10\n\x08subtract\x18\x03 \x01(\x05\x12\x10\n\x08\x64ivision\x18\x04 \x01(\x05\"\x14\n\x12HealthCheckRequest\"\x12\n\x10HealthCheckReply2x\n\tCalculate\x12\x38\n\x0chealth_check\x12\x13.HealthCheckRequest\x1a\x11.HealthCheckReply\"\x00\x12\x31\n\tcalculate\x12\x11.CalculateRequest\x1a\x0f.CalculateReply\"\x00\x62\x06proto3'
)




_CALCULATEREQUEST = _descriptor.Descriptor(
  name='CalculateRequest',
  full_name='CalculateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_number', full_name='CalculateRequest.first_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second_number', full_name='CalculateRequest.second_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=97,
)


_CALCULATEREPLY_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='CalculateReply.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='add', full_name='CalculateReply.Result.add', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiply', full_name='CalculateReply.Result.multiply', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtract', full_name='CalculateReply.Result.subtract', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='division', full_name='CalculateReply.Result.division', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=233,
)

_CALCULATEREPLY = _descriptor.Descriptor(
  name='CalculateReply',
  full_name='CalculateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CalculateReply.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CALCULATEREPLY_RESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=233,
)


_HEALTHCHECKREQUEST = _descriptor.Descriptor(
  name='HealthCheckRequest',
  full_name='HealthCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=255,
)


_HEALTHCHECKREPLY = _descriptor.Descriptor(
  name='HealthCheckReply',
  full_name='HealthCheckReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=275,
)

_CALCULATEREPLY_RESULT.containing_type = _CALCULATEREPLY
_CALCULATEREPLY.fields_by_name['result'].message_type = _CALCULATEREPLY_RESULT
DESCRIPTOR.message_types_by_name['CalculateRequest'] = _CALCULATEREQUEST
DESCRIPTOR.message_types_by_name['CalculateReply'] = _CALCULATEREPLY
DESCRIPTOR.message_types_by_name['HealthCheckRequest'] = _HEALTHCHECKREQUEST
DESCRIPTOR.message_types_by_name['HealthCheckReply'] = _HEALTHCHECKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculateRequest = _reflection.GeneratedProtocolMessageType('CalculateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATEREQUEST,
  '__module__' : 'modules.protos.calculate_pb2'
  # @@protoc_insertion_point(class_scope:CalculateRequest)
  })
_sym_db.RegisterMessage(CalculateRequest)

CalculateReply = _reflection.GeneratedProtocolMessageType('CalculateReply', (_message.Message,), {

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR' : _CALCULATEREPLY_RESULT,
    '__module__' : 'modules.protos.calculate_pb2'
    # @@protoc_insertion_point(class_scope:CalculateReply.Result)
    })
  ,
  'DESCRIPTOR' : _CALCULATEREPLY,
  '__module__' : 'modules.protos.calculate_pb2'
  # @@protoc_insertion_point(class_scope:CalculateReply)
  })
_sym_db.RegisterMessage(CalculateReply)
_sym_db.RegisterMessage(CalculateReply.Result)

HealthCheckRequest = _reflection.GeneratedProtocolMessageType('HealthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREQUEST,
  '__module__' : 'modules.protos.calculate_pb2'
  # @@protoc_insertion_point(class_scope:HealthCheckRequest)
  })
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckReply = _reflection.GeneratedProtocolMessageType('HealthCheckReply', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREPLY,
  '__module__' : 'modules.protos.calculate_pb2'
  # @@protoc_insertion_point(class_scope:HealthCheckReply)
  })
_sym_db.RegisterMessage(HealthCheckReply)



_CALCULATE = _descriptor.ServiceDescriptor(
  name='Calculate',
  full_name='Calculate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=277,
  serialized_end=397,
  methods=[
  _descriptor.MethodDescriptor(
    name='health_check',
    full_name='Calculate.health_check',
    index=0,
    containing_service=None,
    input_type=_HEALTHCHECKREQUEST,
    output_type=_HEALTHCHECKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='calculate',
    full_name='Calculate.calculate',
    index=1,
    containing_service=None,
    input_type=_CALCULATEREQUEST,
    output_type=_CALCULATEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATE)

DESCRIPTOR.services_by_name['Calculate'] = _CALCULATE

# @@protoc_insertion_point(module_scope)
