# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from modules.protos import calculate_pb2 as modules_dot_protos_dot_calculate__pb2


class CalculateStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.health_check = channel.unary_unary(
                '/Calculate/health_check',
                request_serializer=modules_dot_protos_dot_calculate__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=modules_dot_protos_dot_calculate__pb2.HealthCheckReply.FromString,
                )
        self.calculate = channel.unary_unary(
                '/Calculate/calculate',
                request_serializer=modules_dot_protos_dot_calculate__pb2.CalculateRequest.SerializeToString,
                response_deserializer=modules_dot_protos_dot_calculate__pb2.CalculateReply.FromString,
                )


class CalculateServicer(object):
    """Missing associated documentation comment in .proto file"""

    def health_check(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def calculate(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'health_check': grpc.unary_unary_rpc_method_handler(
                    servicer.health_check,
                    request_deserializer=modules_dot_protos_dot_calculate__pb2.HealthCheckRequest.FromString,
                    response_serializer=modules_dot_protos_dot_calculate__pb2.HealthCheckReply.SerializeToString,
            ),
            'calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.calculate,
                    request_deserializer=modules_dot_protos_dot_calculate__pb2.CalculateRequest.FromString,
                    response_serializer=modules_dot_protos_dot_calculate__pb2.CalculateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calculate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculate(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def health_check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculate/health_check',
            modules_dot_protos_dot_calculate__pb2.HealthCheckRequest.SerializeToString,
            modules_dot_protos_dot_calculate__pb2.HealthCheckReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculate/calculate',
            modules_dot_protos_dot_calculate__pb2.CalculateRequest.SerializeToString,
            modules_dot_protos_dot_calculate__pb2.CalculateReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
